---
- name: restart apache
  service:
    name: apache2
    state: stopped
  become: true

- service:
    name: apache2
    state: started
  become: true

- name: Restart nginx
  action: service name=nginx state=restarted